version: '3.8'

services:
  postgres:
    container_name: jpa_student
    image: postgres:latest
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "5442:5432"
    restart: unless-stopped

volumes:
  postgres_data:
  postgres_volume:
